# Generated by Django 5.0.1 on 2026-02-18 21:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_pattern', models.JSONField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'focus_blocks',
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['user', 'start_time'], name='focus_block_user_id_95500e_idx')],
            },
        ),
        migrations.CreateModel(
            name='FocusSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('planned_duration', models.IntegerField()),
                ('actual_duration', models.IntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], default='planned', max_length=50)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('distractions', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'focus_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='focus_sessi_user_id_432de6_idx'), models.Index(fields=['start_time'], name='focus_sessi_start_t_e4feaf_idx')],
            },
        ),
    ]
