# Generated by Django 5.0.1 on 2026-02-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_duplicate_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('organization_manager', 'Organization Manager'), ('company_manager', 'Company Manager'), ('employee', 'Employee'), ('user', 'User'), ('admin', 'Admin'), ('operations_manager', 'Operations Manager'), ('manager', 'Manager'), ('candidate', 'Candidate'), ('house_keeping', 'House Keeping'), ('maintenance', 'Maintenance')], default='user', max_length=50),
        ),
    ]
