# Generated by Django 5.0.1

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('technology', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'learning_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='templates.learningtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'template_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='learningtemplate',
            index=models.Index(fields=['created_by'], name='learning_te_created_09f6cf_idx'),
        ),
        migrations.AddIndex(
            model_name='templateassignment',
            index=models.Index(fields=['template'], name='template_as_templat_4bb4b5_idx'),
        ),
        migrations.AddIndex(
            model_name='templateassignment',
            index=models.Index(fields=['user'], name='template_as_user_id_fd6f85_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='templateassignment',
            unique_together={('template', 'user')},
        ),
    ]
