# Generated by Django 5.0.1 on 2026-02-19 17:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['organization'], name='company_org_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['company_manager'], name='company_manager_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['operations_manager'], name='company_ops_manager_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['organization', 'name'], name='company_org_name_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['created_at'], name='company_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['company'], name='dept_company_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company'], name='employee_company_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['user'], name='employee_user_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['status'], name='employee_status_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['email'], name='employee_email_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company', 'status'], name='employee_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company', 'department'], name='employee_company_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['hire_date'], name='employee_hire_date_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['organization_manager'], name='org_manager_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['operations_manager'], name='org_ops_manager_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['created_by'], name='org_created_by_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['created_at'], name='org_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleteam',
            index=models.Index(fields=['company'], name='team_company_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['company'], name='shift_company_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['employee'], name='shift_employee_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['start_time', 'end_time'], name='shift_time_range_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['company', 'start_time'], name='shift_company_time_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['status'], name='shift_status_idx'),
        ),
    ]
